function F = solve(theta,S,gamma,Rd,M,Nr,Ha,n)
delx=1/n;
F = zeros(1,n);
F(1) = theta(2) - 2*theta(1) + theta(2) - ...
       S*sin(gamma)*delx^2*theta(1)^2/(1 + 4*Rd) - ...
       M^2*delx^2*theta(1)/(1 + 4*Rd) - ...
       Nr*delx^2*theta(1)/(1 + 4*Rd) - ...
       Ha*delx^2*theta(1)/(1 + 4*Rd);
for i = 2:n-1
    F(i) = theta(i+1) - 2*theta(i) + theta(i-1) - ...
           S*sin(gamma)*delx^2*theta(i)^2/(1 + 4*Rd) - ...
           M^2*delx^2*theta(i)/(1 + 4*Rd) - ...
           Nr*delx^2*theta(i)/(1 + 4*Rd) - ...
           Ha*delx^2*theta(i)/(1 + 4*Rd);
end
F(n) = 1 - 2*theta(n) + theta(n-1) - ...
       S*sin(gamma)*delx^2*theta(n)^2/(1 + 4*Rd) - ...
       M^2*delx^2*theta(n)/(1 + 4*Rd) - ...
       Nr*delx^2*theta(n)/(1 + 4*Rd) - ...
       Ha*delx^2*theta(n)/(1 + 4*Rd);
end