function F = solve(theta,M,beta,Q,gamma,n)
delx=1/n;
F = zeros(1,n);
F(1) = (1+beta*theta(1))*(theta(2)-2*theta(1)+1)/(delx^2) + ...
       beta*((theta(2)-1)/(2*delx))^2 - M^2*theta(1) + ...
       M^2*Q*(1+gamma*theta(1));
for i = 2:n-1
    F(i) = (1+beta*theta(i))*(theta(i+1)-2*theta(i)+theta(i-1))/(delx^2) ...
           + beta*((theta(i+1)-theta(i-1))/(2*delx))^2 ...
           - M^2*theta(i) + M^2*Q*(1+gamma*theta(i));
end
F(n) = (1+beta*theta(n))*(theta(n-2)-theta(n))/(2*delx^2) + ...
       beta*((theta(n)-theta(n-1))/(2*delx))^2 - ...
       M^2*theta(n) + M^2*Q*(1+gamma*theta(n));
end