function theta = solve(X,n,beta,M,gamma,Q)
%UNTITLED20 Summary of this function goes here
%   Detailed explanation goes here
if n==0
    theta = 1 - ((1-X.^2)*(...
        5*(1+beta) + 2*M^2*(1-gamma*Q) - ...
           ( (5*(1+beta) + 2*M^2*(1-gamma*Q))^2 - ...
              -20*beta*M^2*(1-Q*(1+gamma))...
           )^(0.5)...
        )/(4*beta));
else
    theta = 1 - ((1-X.^2)*(...
        5*(1+beta) + 2*M^2*(2-gamma*Q) - ...
           ( (5*(1+beta) + 2*M^2*(2-gamma*Q))^2 - ...
              -20*beta*M^2*(beta^2+(6*M^2/7))*(1-Q*(1+gamma))...
           )^(0.5)...
        )/(4*(beta^2+(6*M^2/7))));
end


end